<h1>增加投票选项</h1>
<form action='/admin/additem' method='post'>
<table>
<tr><td>name</td><td><input type='text' name='name'/></td></tr>
<tr><td>描述</td><td>
<textarea rows='5' cols='30' name='description'>
</textarea>
</td></tr>
<tr><td>初始化投票数</td><td><input type='text' name='vote_count' /></td></tr>
<tr><td><input type="submit" value='添加' /></td>
<td><input type='reset' value='重新填写' /></td></tr>
</table>
</form>